---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql
    spec:
      containers:
        - name: database
          image: mysql
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: sairam
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: sql-storage
      volumes:
        - name: sql-storage
          persistentVolumeClaim:
            claimName: vp-claim

